# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.metrics_api import MetricsApi


class TestMetricsApi(unittest.TestCase):
    """MetricsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetricsApi()

    def tearDown(self) -> None:
        pass

    def test_get_v1_metrics_incidents(self) -> None:
        """Test case for get_v1_metrics_incidents

        List incident metrics
        """
        pass

    def test_get_v1_metrics_infra_type(self) -> None:
        """Test case for get_v1_metrics_infra_type

        List metrics for a component type
        """
        pass

    def test_get_v1_metrics_infra_type_infra_id(self) -> None:
        """Test case for get_v1_metrics_infra_type_infra_id

        Show metrics for a component
        """
        pass

    def test_get_v1_metrics_mttx(self) -> None:
        """Test case for get_v1_metrics_mttx

        """
        pass

    def test_get_v1_metrics_retrospectives(self) -> None:
        """Test case for get_v1_metrics_retrospectives

        List retrospective metrics
        """
        pass

    def test_get_v1_metrics_user_involvements(self) -> None:
        """Test case for get_v1_metrics_user_involvements

        List user metrics
        """
        pass


if __name__ == '__main__':
    unittest.main()
