
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-25T13:37:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "bef077cfb019dd2608e14edab047d37d75dfba61",
 "version": "2.0a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
