# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.infrastructures_api import InfrastructuresApi


class TestInfrastructuresApi(unittest.TestCase):
    """InfrastructuresApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InfrastructuresApi()

    def tearDown(self) -> None:
        pass

    def test_get_v1_infrastructures(self) -> None:
        """Test case for get_v1_infrastructures

        Lists functionality, service and environment objects
        """
        pass


if __name__ == '__main__':
    unittest.main()
