# Generated by Django 4.2.9 on 2024-09-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_tenant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='billing_contact_address',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='billing_contact_city',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='billing_contact_country',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='billing_contact_email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='billing_contact_name',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='billing_contact_postalcode',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='billing_contact_state_province',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='billing_contact_telephone',
        ),
    ]
