# -*- coding: utf-8 -*-
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

__all__ = (
'AccountStatusEnum',
'AccountTypeEnum',
'AdGroupAdEngineStatusEnum',
'AdGroupAdRotationModeEnum',
'AdGroupAdStatusEnum',
'AdGroupCriterionEngineStatusEnum',
'AdGroupCriterionStatusEnum',
'AdGroupEngineStatusEnum',
'AdGroupStatusEnum',
'AdGroupTypeEnum',
'AdNetworkTypeEnum',
'AdServingOptimizationStatusEnum',
'AdStrengthEnum',
'AdTypeEnum',
'AdvertisingChannelSubTypeEnum',
'AdvertisingChannelTypeEnum',
'AgeRangeTypeEnum',
'AssetEngineStatusEnum',
'AssetFieldTypeEnum',
'AssetGroupStatusEnum',
'AssetLinkStatusEnum',
'AssetSetAssetStatusEnum',
'AssetSetLinkStatusEnum',
'AssetStatusEnum',
'AssetTypeEnum',
'AttributionModelEnum',
'AttributionTypeEnum',
'BiddingStrategyStatusEnum',
'BiddingStrategySystemStatusEnum',
'BiddingStrategyTypeEnum',
'BudgetDeliveryMethodEnum',
'BudgetPeriodEnum',
'CallConversionReportingStateEnum',
'CallToActionTypeEnum',
'CampaignCriterionStatusEnum',
'CampaignServingStatusEnum',
'CampaignStatusEnum',
'ConversionActionCategoryEnum',
'ConversionActionStatusEnum',
'ConversionActionTypeEnum',
'ConversionCustomVariableCardinalityEnum',
'ConversionCustomVariableFamilyEnum',
'ConversionCustomVariableStatusEnum',
'ConversionStatusEnum',
'ConversionTrackingStatusEnum',
'CriterionTypeEnum',
'CustomColumnRenderTypeEnum',
'CustomColumnValueTypeEnum',
'CustomerStatusEnum',
'DataDrivenModelStatusEnum',
'DayOfWeekEnum',
'DeviceEnum',
'FloodlightVariableDataTypeEnum',
'FloodlightVariableTypeEnum',
'GenderTypeEnum',
'GeoTargetConstantStatusEnum',
'InteractionEventTypeEnum',
'KeywordMatchTypeEnum',
'LabelStatusEnum',
'ListingGroupFilterBiddingCategoryLevelEnum',
'ListingGroupFilterCustomAttributeIndexEnum',
'ListingGroupFilterProductChannelEnum',
'ListingGroupFilterProductConditionEnum',
'ListingGroupFilterProductTypeLevelEnum',
'ListingGroupFilterTypeEnum',
'ListingGroupFilterVerticalEnum',
'ListingGroupTypeEnum',
'LocationGroupRadiusUnitsEnum',
'LocationOwnershipTypeEnum',
'ManagerLinkStatusEnum',
'MimeTypeEnum',
'MinuteOfHourEnum',
'MobileAppVendorEnum',
'NegativeGeoTargetTypeEnum',
'OptimizationGoalTypeEnum',
'PositiveGeoTargetTypeEnum',
'ProductBiddingCategoryLevelEnum',
'ProductBiddingCategoryStatusEnum',
'ProductChannelEnum',
'ProductChannelExclusivityEnum',
'ProductConditionEnum',
'QualityScoreBucketEnum',
'SearchAds360FieldCategoryEnum',
'SearchAds360FieldDataTypeEnum',
'ServedAssetFieldTypeEnum',
'SummaryRowSettingEnum',
'TargetImpressionShareLocationEnum',
'TargetingDimensionEnum',
'UserListTypeEnum',
'WebpageConditionOperandEnum',
'WebpageConditionOperatorEnum',
)
