# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v1_webhooks_webhook_id(self) -> None:
        """Test case for delete_v1_webhooks_webhook_id

        Delete a specific webhook
        """
        pass

    def test_get_v1_webhooks(self) -> None:
        """Test case for get_v1_webhooks

        Lists webhooks
        """
        pass

    def test_get_v1_webhooks_webhook_id(self) -> None:
        """Test case for get_v1_webhooks_webhook_id

        Retrieve a specific webhook
        """
        pass

    def test_get_v1_webhooks_webhook_id_deliveries(self) -> None:
        """Test case for get_v1_webhooks_webhook_id_deliveries

        """
        pass

    def test_patch_v1_webhooks_webhook_id(self) -> None:
        """Test case for patch_v1_webhooks_webhook_id

        Update a specific webhook
        """
        pass

    def test_post_v1_webhooks(self) -> None:
        """Test case for post_v1_webhooks

        Create webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
