# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.nunc_email_subscribers_entity import NuncEmailSubscribersEntity

class TestNuncEmailSubscribersEntity(unittest.TestCase):
    """NuncEmailSubscribersEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NuncEmailSubscribersEntity:
        """Test NuncEmailSubscribersEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NuncEmailSubscribersEntity`
        """
        model = NuncEmailSubscribersEntity()
        if include_optional:
            return NuncEmailSubscribersEntity(
                id = '',
                email = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return NuncEmailSubscribersEntity(
        )
        """

    def testNuncEmailSubscribersEntity(self):
        """Test NuncEmailSubscribersEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
