# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.scim_api import ScimApi


class TestScimApi(unittest.TestCase):
    """ScimApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScimApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v1_scim_v2_groups_id(self) -> None:
        """Test case for delete_v1_scim_v2_groups_id

        Deletes a Team (via the Group protocol)
        """
        pass

    def test_delete_v1_scim_v2_users_id(self) -> None:
        """Test case for delete_v1_scim_v2_users_id

        Deletes a User using SCIM protocol
        """
        pass

    def test_get_v1_scim_v2_groups(self) -> None:
        """Test case for get_v1_scim_v2_groups

        List all Teams (via the Group protocol)
        """
        pass

    def test_get_v1_scim_v2_groups_id(self) -> None:
        """Test case for get_v1_scim_v2_groups_id

        Lists a Team (via the Group protocol)
        """
        pass

    def test_get_v1_scim_v2_users(self) -> None:
        """Test case for get_v1_scim_v2_users

        Gets a list of Users using SCIM protocol
        """
        pass

    def test_get_v1_scim_v2_users_id(self) -> None:
        """Test case for get_v1_scim_v2_users_id

        Lists a User (via the User protocol)
        """
        pass

    def test_post_v1_scim_v2_groups(self) -> None:
        """Test case for post_v1_scim_v2_groups

        Creates a new Team (via the Group protocol) and assigns members to that team.
        """
        pass

    def test_post_v1_scim_v2_users(self) -> None:
        """Test case for post_v1_scim_v2_users

        Creates a new User using SCIM protocol
        """
        pass

    def test_put_v1_scim_v2_groups_id(self) -> None:
        """Test case for put_v1_scim_v2_groups_id

        Updates a Team (via the Group protocol) and assigns members to that team.
        """
        pass

    def test_put_v1_scim_v2_users_id(self) -> None:
        """Test case for put_v1_scim_v2_users_id

        Updates a User using SCIM protocol
        """
        pass


if __name__ == '__main__':
    unittest.main()
