# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.patch_v1_conversations_conversation_id_comments_comment_id import PatchV1ConversationsConversationIdCommentsCommentId

class TestPatchV1ConversationsConversationIdCommentsCommentId(unittest.TestCase):
    """PatchV1ConversationsConversationIdCommentsCommentId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchV1ConversationsConversationIdCommentsCommentId:
        """Test PatchV1ConversationsConversationIdCommentsCommentId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchV1ConversationsConversationIdCommentsCommentId`
        """
        model = PatchV1ConversationsConversationIdCommentsCommentId()
        if include_optional:
            return PatchV1ConversationsConversationIdCommentsCommentId(
                body = ''
            )
        else:
            return PatchV1ConversationsConversationIdCommentsCommentId(
        )
        """

    def testPatchV1ConversationsConversationIdCommentsCommentId(self):
        """Test PatchV1ConversationsConversationIdCommentsCommentId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
