"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    endrestrictionrequestcreate as components_endrestrictionrequestcreate,
    httpmetadata as components_httpmetadata,
)
from ascend_sdk.models.errors import status as errors_status
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class AccountsEndRestrictionRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    restriction_id: str
    r"""The restriction id."""
    end_restriction_request_create: components_endrestrictionrequestcreate.EndRestrictionRequestCreateTypedDict


class AccountsEndRestrictionRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""
    restriction_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The restriction id."""
    end_restriction_request_create: Annotated[
        components_endrestrictionrequestcreate.EndRestrictionRequestCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class AccountsEndRestrictionResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    status: NotRequired[errors_status.Status]
    r"""INVALID_ARGUMENT: The request is not valid, additional information may be present in the BadRequest details."""


class AccountsEndRestrictionResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None
    status: Optional[errors_status.Status] = None
    r"""INVALID_ARGUMENT: The request is not valid, additional information may be present in the BadRequest details."""
