"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    achwithdrawalschedule as components_achwithdrawalschedule,
    achwithdrawalschedulecreate as components_achwithdrawalschedulecreate,
    httpmetadata as components_httpmetadata,
)
from ascend_sdk.models.errors import status as errors_status
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class AchWithdrawalSchedulesCreateAchWithdrawalScheduleRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    ach_withdrawal_schedule_create: components_achwithdrawalschedulecreate.AchWithdrawalScheduleCreateTypedDict


class AchWithdrawalSchedulesCreateAchWithdrawalScheduleRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""
    ach_withdrawal_schedule_create: Annotated[
        components_achwithdrawalschedulecreate.AchWithdrawalScheduleCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class AchWithdrawalSchedulesCreateAchWithdrawalScheduleResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    ach_withdrawal_schedule: NotRequired[
        components_achwithdrawalschedule.AchWithdrawalScheduleTypedDict
    ]
    r"""OK"""
    status: NotRequired[errors_status.Status]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class AchWithdrawalSchedulesCreateAchWithdrawalScheduleResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None
    ach_withdrawal_schedule: Optional[
        components_achwithdrawalschedule.AchWithdrawalSchedule
    ] = None
    r"""OK"""
    status: Optional[errors_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
