"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.models.components import (
    achwithdrawal as components_achwithdrawal,
    forcereturnachwithdrawalrequestcreate as components_forcereturnachwithdrawalrequestcreate,
    httpmetadata as components_httpmetadata,
)
from ascend_sdk.models.errors import status as errors_status
from ascend_sdk.types import BaseModel
from ascend_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Optional, TypedDict
from typing_extensions import Annotated, NotRequired


class AchWithdrawalsForceReturnAchWithdrawalRequestTypedDict(TypedDict):
    account_id: str
    r"""The account id."""
    ach_withdrawal_id: str
    r"""The achWithdrawal id."""
    force_return_ach_withdrawal_request_create: components_forcereturnachwithdrawalrequestcreate.ForceReturnAchWithdrawalRequestCreateTypedDict


class AchWithdrawalsForceReturnAchWithdrawalRequest(BaseModel):
    account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The account id."""
    ach_withdrawal_id: Annotated[
        str,
        pydantic.Field(alias="achWithdrawal_id"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""The achWithdrawal id."""
    force_return_ach_withdrawal_request_create: Annotated[
        components_forcereturnachwithdrawalrequestcreate.ForceReturnAchWithdrawalRequestCreate,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class AchWithdrawalsForceReturnAchWithdrawalResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    ach_withdrawal: NotRequired[components_achwithdrawal.AchWithdrawalTypedDict]
    r"""OK"""
    status: NotRequired[errors_status.Status]
    r"""INVALID_ARGUMENT: The request has an invalid argument."""


class AchWithdrawalsForceReturnAchWithdrawalResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None
    ach_withdrawal: Optional[components_achwithdrawal.AchWithdrawal] = None
    r"""OK"""
    status: Optional[errors_status.Status] = None
    r"""INVALID_ARGUMENT: The request has an invalid argument."""
