__title__ = "datahorse"
__description__ = "Your Data Assistant"
__version__ = "0.1.1"
__author__ = "DeDolphins"
__author_email__ = "info@datahorse.ai"
__license__ = "creativeml-openrail-m"
__url__ = "https://datahorse.ai"