# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/tenant.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'proto/tenant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import integration_pb2 as proto_dot_integration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/tenant.proto\x12\x05proto\x1a\x17proto/integration.proto\"m\n\x0c\x42ucketConfig\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12\x14\n\x0c\x65ndpoint_url\x18\x03 \x01(\t\x12\'\n\x0bintegration\x18\x04 \x01(\x0b\x32\x12.proto.Integration\"\xb9\x01\n\x14StorageConfiguration\x12\x15\n\rupload_bucket\x18\x01 \x01(\t\x12\x14\n\x0c\x65ndpoint_url\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t\x12\x15\n\rupload_prefix\x18\x04 \x01(\t\x12\'\n\x0bintegration\x18\x05 \x01(\x0b\x32\x12.proto.Integration\x12$\n\x07\x62uckets\x18\x06 \x03(\x0b\x32\x13.proto.BucketConfig\"\xb8\x01\n\x14\x43omputeConfiguration\x12\x12\n\nlog_bucket\x18\x01 \x01(\t\x12\x12\n\nlog_prefix\x18\x02 \x01(\t\x12\x15\n\rresult_bucket\x18\x03 \x01(\t\x12\x15\n\rresult_prefix\x18\x04 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\x12\'\n\x0bintegration\x18\x06 \x01(\x0b\x32\x12.proto.Integration\x12\x11\n\tqueue_arn\x18\x07 \x01(\t\" \n\x10ListKeysResponse\x12\x0c\n\x04keys\x18\x01 \x03(\t\"{\n\x14\x46\x65\x61tureFlagsResponse\x12\x35\n\x05\x66lags\x18\x01 \x03(\x0b\x32&.proto.FeatureFlagsResponse.FlagsEntry\x1a,\n\nFlagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\";\n\x13ListBucketsResponse\x12$\n\x07\x62uckets\x18\x01 \x03(\x0b\x32\x13.proto.BucketConfigB\x0eZ\x0cserver/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tenant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014server/proto'
  _globals['_FEATUREFLAGSRESPONSE_FLAGSENTRY']._loaded_options = None
  _globals['_FEATUREFLAGSRESPONSE_FLAGSENTRY']._serialized_options = b'8\001'
  _globals['_BUCKETCONFIG']._serialized_start=54
  _globals['_BUCKETCONFIG']._serialized_end=163
  _globals['_STORAGECONFIGURATION']._serialized_start=166
  _globals['_STORAGECONFIGURATION']._serialized_end=351
  _globals['_COMPUTECONFIGURATION']._serialized_start=354
  _globals['_COMPUTECONFIGURATION']._serialized_end=538
  _globals['_LISTKEYSRESPONSE']._serialized_start=540
  _globals['_LISTKEYSRESPONSE']._serialized_end=572
  _globals['_FEATUREFLAGSRESPONSE']._serialized_start=574
  _globals['_FEATUREFLAGSRESPONSE']._serialized_end=697
  _globals['_FEATUREFLAGSRESPONSE_FLAGSENTRY']._serialized_start=653
  _globals['_FEATUREFLAGSRESPONSE_FLAGSENTRY']._serialized_end=697
  _globals['_LISTBUCKETSRESPONSE']._serialized_start=699
  _globals['_LISTBUCKETSRESPONSE']._serialized_end=758
# @@protoc_insertion_point(module_scope)
