import numpy as np

from typing import Tuple

class DataFrameF64:
    @staticmethod
    def new(
        index: np.ndarray,
        columns: np.ndarray,
        data: np.ndarray,
    ) -> DataFrameF64: ...
    @property
    def index(self) -> np.ndarray: ...
    @property
    def columns(self) -> np.ndarray: ...
    @property
    def values(self) -> np.ndarray: ...
    @property
    def shape(self) -> Tuple[int, int]: ...
    def with_data(self, data: np.ndarray) -> DataFrameF64: ...
    def mean_axis1(self) -> np.ndarray: ...
    def corr_with_axis1(self, other: np.ndarray) -> np.ndarray: ...
