# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: boson_v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import boson.boson_core_pb2 as boson__core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62oson_v1.proto\x12\x0f\x62osonproviderv1\x1a\x10\x62oson_core.proto2\xef\x01\n\x0f\x42osonProviderV1\x12R\n\x0b\x44\x61tasetInfo\x12\x1f.bosoncorev1.DatasetInfoRequest\x1a .bosoncorev1.DatasetInfoResponse\"\x00\x12\x43\n\x06Search\x12\x1a.bosoncorev1.SearchRequest\x1a\x1b.bosoncorev1.SearchResponse\"\x00\x12\x43\n\x06Pixels\x12\x1a.bosoncorev1.PixelsRequest\x1a\x1b.bosoncorev1.RasterResponse\"\x00\x42/Z-github.com/seerai/boson-core/providers/remoteb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'boson_v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-github.com/seerai/boson-core/providers/remote'
  _BOSONPROVIDERV1._serialized_start=54
  _BOSONPROVIDERV1._serialized_end=293
# @@protoc_insertion_point(module_scope)
