"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ascend_sdk.types import BaseModel
import pydantic
from typing import List, TypedDict
from typing_extensions import Annotated


class OtherAccountsCreateTypedDict(TypedDict):
    r"""A customer-disclosed list of other Apex-held accounts owned by the Entity applicant at the time of this account's application; expressed as zero, one, or many account numbers"""

    account_numbers: List[str]
    r"""Other account numbers held at this Broker-Dealer"""
    entity_owner_has_other_accounts_at_this_broker_dealer: bool
    r"""The entity owner has other accounts at this Broker-Dealer"""
    owner_has_other_accounts_at_this_broker_dealer: bool
    r"""The owner has other accounts at this Broker-Dealer"""


class OtherAccountsCreate(BaseModel):
    r"""A customer-disclosed list of other Apex-held accounts owned by the Entity applicant at the time of this account's application; expressed as zero, one, or many account numbers"""

    account_numbers: List[str]
    r"""Other account numbers held at this Broker-Dealer"""
    entity_owner_has_other_accounts_at_this_broker_dealer: Annotated[
        bool,
        pydantic.Field(
            deprecated="warning: ** DEPRECATED ** - This will be removed in a future release, please migrate away from it as soon as possible."
        ),
    ]
    r"""The entity owner has other accounts at this Broker-Dealer"""
    owner_has_other_accounts_at_this_broker_dealer: bool
    r"""The owner has other accounts at this Broker-Dealer"""
