"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .immediatefamilymembercreate import (
    ImmediateFamilyMemberCreate,
    ImmediateFamilyMemberCreateTypedDict,
)
from ascend_sdk.types import BaseModel
from typing import List, Optional, TypedDict
from typing_extensions import NotRequired


class RelatedPepCreateTypedDict(TypedDict):
    r"""Detail around the Related Politically Exposed Person."""

    immediate_family_members: NotRequired[List[ImmediateFamilyMemberCreateTypedDict]]
    r"""Information about the immediate family members of the related politically exposed person"""
    organization: NotRequired[str]
    r"""The organization a politically exposed person is associated with causing them to be considered politically exposed"""
    pep_name: NotRequired[str]
    r"""The name of the related politically exposed person"""
    title: NotRequired[str]
    r"""The title of the related politically exposed person"""


class RelatedPepCreate(BaseModel):
    r"""Detail around the Related Politically Exposed Person."""

    immediate_family_members: Optional[List[ImmediateFamilyMemberCreate]] = None
    r"""Information about the immediate family members of the related politically exposed person"""
    organization: Optional[str] = None
    r"""The organization a politically exposed person is associated with causing them to be considered politically exposed"""
    pep_name: Optional[str] = None
    r"""The name of the related politically exposed person"""
    title: Optional[str] = None
    r"""The title of the related politically exposed person"""
