# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.post_v1_incidents_incident_id_generic_chat_messages import PostV1IncidentsIncidentIdGenericChatMessages

class TestPostV1IncidentsIncidentIdGenericChatMessages(unittest.TestCase):
    """PostV1IncidentsIncidentIdGenericChatMessages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1IncidentsIncidentIdGenericChatMessages:
        """Test PostV1IncidentsIncidentIdGenericChatMessages
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1IncidentsIncidentIdGenericChatMessages`
        """
        model = PostV1IncidentsIncidentIdGenericChatMessages()
        if include_optional:
            return PostV1IncidentsIncidentIdGenericChatMessages(
                body = '',
                occurred_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                vote_direction = 'up'
            )
        else:
            return PostV1IncidentsIncidentIdGenericChatMessages(
                body = '',
        )
        """

    def testPostV1IncidentsIncidentIdGenericChatMessages(self):
        """Test PostV1IncidentsIncidentIdGenericChatMessages"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
