# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.integrations_statuspage_connection_entity import IntegrationsStatuspageConnectionEntity

class TestIntegrationsStatuspageConnectionEntity(unittest.TestCase):
    """IntegrationsStatuspageConnectionEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationsStatuspageConnectionEntity:
        """Test IntegrationsStatuspageConnectionEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationsStatuspageConnectionEntity`
        """
        model = IntegrationsStatuspageConnectionEntity()
        if include_optional:
            return IntegrationsStatuspageConnectionEntity(
                id = '',
                page_name = '',
                page_id = '',
                conditions = [
                    firehydrant_api_client.models.integrations_statuspage_condition_entity.Integrations_Statuspage_ConditionEntity(
                        condition_id = '', 
                        condition_name = '', 
                        statuspageio_condition = 'operational', )
                    ],
                severities = [
                    firehydrant_api_client.models.integrations_statuspage_severity_entity.Integrations_Statuspage_SeverityEntity(
                        severity_slug = '', 
                        remote_status = '', )
                    ],
                milestone_mappings = [
                    firehydrant_api_client.models.integrations_statuspage_milestone_mapping_entity.Integrations_Statuspage_MilestoneMappingEntity(
                        milestone_id = '', 
                        status = '', )
                    ]
            )
        else:
            return IntegrationsStatuspageConnectionEntity(
        )
        """

    def testIntegrationsStatuspageConnectionEntity(self):
        """Test IntegrationsStatuspageConnectionEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
