# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.nunc_connection_entity import NuncConnectionEntity

class TestNuncConnectionEntity(unittest.TestCase):
    """NuncConnectionEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NuncConnectionEntity:
        """Test NuncConnectionEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NuncConnectionEntity`
        """
        model = NuncConnectionEntity()
        if include_optional:
            return NuncConnectionEntity(
                id = '',
                domain = '',
                company_name = '',
                company_website = '',
                cname = '',
                greeting_title = '',
                greeting_body = '',
                operational_message = '',
                company_tos_url = '',
                primary_color = '',
                secondary_color = '',
                button_background_color = '',
                button_text_color = '',
                link_color = '',
                title = '',
                exposed_fields = '',
                conditions = firehydrant_api_client.models.nunc_condition_entity.NuncConditionEntity(
                    nunc_condition = '', 
                    condition_name = '', 
                    condition_id = '', ),
                components = firehydrant_api_client.models.nunc_component_entity.NuncComponentEntity(
                    infrastructure_type = '', 
                    infrastructure_id = '', 
                    label = '', 
                    position = 56, 
                    component_group_id = '', ),
                component_groups = firehydrant_api_client.models.nunc_component_group_entity.NuncComponentGroupEntity(
                    id = '', 
                    component_group_id = '', 
                    name = '', 
                    position = 56, ),
                logo = firehydrant_api_client.models.media_image_entity.MediaImageEntity(
                    original_url = '', 
                    versions_urls = firehydrant_api_client.models.versions_urls.versions_urls(), ),
                cover_image = firehydrant_api_client.models.media_image_entity.MediaImageEntity(
                    original_url = '', 
                    versions_urls = firehydrant_api_client.models.versions_urls.versions_urls(), ),
                favicon = firehydrant_api_client.models.media_image_entity.MediaImageEntity(
                    original_url = '', 
                    versions_urls = firehydrant_api_client.models.versions_urls.versions_urls(), ),
                open_graph_image = firehydrant_api_client.models.media_image_entity.MediaImageEntity(
                    original_url = '', 
                    versions_urls = firehydrant_api_client.models.versions_urls.versions_urls(), ),
                dark_logo = firehydrant_api_client.models.media_image_entity.MediaImageEntity(
                    original_url = '', 
                    versions_urls = firehydrant_api_client.models.versions_urls.versions_urls(), ),
                enable_histogram = True,
                ui_version = 56,
                links = [
                    firehydrant_api_client.models.links_entity.LinksEntity(
                        id = '', 
                        href_url = '', 
                        icon_url = '', 
                        name = '', )
                    ]
            )
        else:
            return NuncConnectionEntity(
        )
        """

    def testNuncConnectionEntity(self):
        """Test NuncConnectionEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
