# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.patch_v1_severity_matrix import PatchV1SeverityMatrix

class TestPatchV1SeverityMatrix(unittest.TestCase):
    """PatchV1SeverityMatrix unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchV1SeverityMatrix:
        """Test PatchV1SeverityMatrix
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchV1SeverityMatrix`
        """
        model = PatchV1SeverityMatrix()
        if include_optional:
            return PatchV1SeverityMatrix(
                summary = '',
                data = [
                    firehydrant_api_client.models.patch_v1_severity_matrix_data_inner.patchV1SeverityMatrix_data_inner(
                        severity = '', 
                        impact_id = '', 
                        condition_id = '', )
                    ]
            )
        else:
            return PatchV1SeverityMatrix(
                data = [
                    firehydrant_api_client.models.patch_v1_severity_matrix_data_inner.patchV1SeverityMatrix_data_inner(
                        severity = '', 
                        impact_id = '', 
                        condition_id = '', )
                    ],
        )
        """

    def testPatchV1SeverityMatrix(self):
        """Test PatchV1SeverityMatrix"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
