# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.patch_v1_functionalities_functionality_id_owner import PatchV1FunctionalitiesFunctionalityIdOwner

class TestPatchV1FunctionalitiesFunctionalityIdOwner(unittest.TestCase):
    """PatchV1FunctionalitiesFunctionalityIdOwner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchV1FunctionalitiesFunctionalityIdOwner:
        """Test PatchV1FunctionalitiesFunctionalityIdOwner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchV1FunctionalitiesFunctionalityIdOwner`
        """
        model = PatchV1FunctionalitiesFunctionalityIdOwner()
        if include_optional:
            return PatchV1FunctionalitiesFunctionalityIdOwner(
                id = ''
            )
        else:
            return PatchV1FunctionalitiesFunctionalityIdOwner(
                id = '',
        )
        """

    def testPatchV1FunctionalitiesFunctionalityIdOwner(self):
        """Test PatchV1FunctionalitiesFunctionalityIdOwner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
