# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.post_v1_functionalities import PostV1Functionalities

class TestPostV1Functionalities(unittest.TestCase):
    """PostV1Functionalities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1Functionalities:
        """Test PostV1Functionalities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1Functionalities`
        """
        model = PostV1Functionalities()
        if include_optional:
            return PostV1Functionalities(
                name = '',
                description = '',
                services = [
                    firehydrant_api_client.models.post_v1_functionalities_services_inner.postV1Functionalities_services_inner(
                        id = '', )
                    ],
                labels = {
                    'key' : ''
                    },
                alert_on_add = True,
                auto_add_responding_team = True,
                external_resources = [
                    firehydrant_api_client.models.post_v1_functionalities_external_resources_inner.postV1Functionalities_external_resources_inner(
                        remote_id = '', 
                        connection_type = '', )
                    ],
                links = [
                    firehydrant_api_client.models.post_v1_services_links_inner.postV1Services_links_inner(
                        name = '', 
                        href_url = '', 
                        icon_url = '', )
                    ],
                owner = firehydrant_api_client.models.post_v1_services_owner.postV1Services_owner(
                    id = '', ),
                teams = [
                    firehydrant_api_client.models.post_v1_services_teams_inner.postV1Services_teams_inner(
                        id = '', )
                    ]
            )
        else:
            return PostV1Functionalities(
                name = '',
        )
        """

    def testPostV1Functionalities(self):
        """Test PostV1Functionalities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
