# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.metrics_infrastructure_metrics_entity import MetricsInfrastructureMetricsEntity

class TestMetricsInfrastructureMetricsEntity(unittest.TestCase):
    """MetricsInfrastructureMetricsEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetricsInfrastructureMetricsEntity:
        """Test MetricsInfrastructureMetricsEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetricsInfrastructureMetricsEntity`
        """
        model = MetricsInfrastructureMetricsEntity()
        if include_optional:
            return MetricsInfrastructureMetricsEntity(
                id = '',
                name = '',
                mttd = 56,
                mtta = 56,
                mttm = 56,
                mttr = 56,
                count = 56,
                total_time = 56
            )
        else:
            return MetricsInfrastructureMetricsEntity(
        )
        """

    def testMetricsInfrastructureMetricsEntity(self):
        """Test MetricsInfrastructureMetricsEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
