# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.ticketing_project_field_map_body_entity import TicketingProjectFieldMapBodyEntity

class TestTicketingProjectFieldMapBodyEntity(unittest.TestCase):
    """TicketingProjectFieldMapBodyEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TicketingProjectFieldMapBodyEntity:
        """Test TicketingProjectFieldMapBodyEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TicketingProjectFieldMapBodyEntity`
        """
        model = TicketingProjectFieldMapBodyEntity()
        if include_optional:
            return TicketingProjectFieldMapBodyEntity(
                strategy = 'basic',
                external_field = '',
                external_value = firehydrant_api_client.models.ticketing_project_field_map_external_value_entity.Ticketing_ProjectFieldMapExternalValueEntity(
                    type = 'literal', 
                    value = '', 
                    attribute = '', 
                    presentation = '', ),
                user_data = firehydrant_api_client.models.user_data.user_data(),
                cases = [
                    firehydrant_api_client.models.ticketing_project_field_map_cases_entity.Ticketing_ProjectFieldMapCasesEntity(
                        logic = firehydrant_api_client.models.logic.logic(), 
                        external_value = firehydrant_api_client.models.ticketing_project_field_map_external_value_entity.Ticketing_ProjectFieldMapExternalValueEntity(
                            type = 'literal', 
                            value = '', 
                            attribute = '', 
                            presentation = '', ), )
                    ],
                var_else = firehydrant_api_client.models.ticketing_project_field_map_cases_else_entity.Ticketing_ProjectFieldMapCasesElseEntity(
                    external_value = firehydrant_api_client.models.ticketing_project_field_map_external_value_entity.Ticketing_ProjectFieldMapExternalValueEntity(
                        type = 'literal', 
                        value = '', 
                        attribute = '', 
                        presentation = '', ), )
            )
        else:
            return TicketingProjectFieldMapBodyEntity(
        )
        """

    def testTicketingProjectFieldMapBodyEntity(self):
        """Test TicketingProjectFieldMapBodyEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
