# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.post_v1_runbooks_owner import PostV1RunbooksOwner

class TestPostV1RunbooksOwner(unittest.TestCase):
    """PostV1RunbooksOwner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1RunbooksOwner:
        """Test PostV1RunbooksOwner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1RunbooksOwner`
        """
        model = PostV1RunbooksOwner()
        if include_optional:
            return PostV1RunbooksOwner(
                id = ''
            )
        else:
            return PostV1RunbooksOwner(
                id = '',
        )
        """

    def testPostV1RunbooksOwner(self):
        """Test PostV1RunbooksOwner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
