# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.put_v1_post_mortems_questions_questions_inner import PutV1PostMortemsQuestionsQuestionsInner

class TestPutV1PostMortemsQuestionsQuestionsInner(unittest.TestCase):
    """PutV1PostMortemsQuestionsQuestionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutV1PostMortemsQuestionsQuestionsInner:
        """Test PutV1PostMortemsQuestionsQuestionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutV1PostMortemsQuestionsQuestionsInner`
        """
        model = PutV1PostMortemsQuestionsQuestionsInner()
        if include_optional:
            return PutV1PostMortemsQuestionsQuestionsInner(
                id = '',
                title = '',
                tooltip = ''
            )
        else:
            return PutV1PostMortemsQuestionsQuestionsInner(
        )
        """

    def testPutV1PostMortemsQuestionsQuestionsInner(self):
        """Test PutV1PostMortemsQuestionsQuestionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
