# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.current_user_api import CurrentUserApi


class TestCurrentUserApi(unittest.TestCase):
    """CurrentUserApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CurrentUserApi()

    def tearDown(self) -> None:
        pass

    def test_get_v1_current_user(self) -> None:
        """Test case for get_v1_current_user

        """
        pass


if __name__ == '__main__':
    unittest.main()
