# Generated by Django 5.0.8 on 2024-09-19 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208_squashed_0036_auto_20240311_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Meta name')),
                ('content', models.CharField(max_length=255, verbose_name='Meta content')),
            ],
            options={
                'verbose_name': 'Meta Tag',
                'verbose_name_plural': 'Meta Tags',
            },
        ),
        migrations.CreateModel(
            name='OpenGraphMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=100, verbose_name='OG property')),
                ('content', models.CharField(max_length=255, verbose_name='OG content')),
            ],
            options={
                'verbose_name': 'Open Graph Meta',
                'verbose_name_plural': 'Open Graph Meta',
            },
        ),
        migrations.CreateModel(
            name='TwitterCardMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Twitter Card name')),
                ('content', models.CharField(max_length=255, verbose_name='Twitter Card content')),
            ],
            options={
                'verbose_name': 'Twitter Card Meta',
                'verbose_name_plural': 'Twitter Card Meta',
            },
        ),
        migrations.CreateModel(
            name='SeoExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('meta_tags', models.ManyToManyField(blank=True, related_name='seo_extensions', to='djangocms_seo.metatag')),
                ('og_meta', models.ManyToManyField(blank=True, related_name='seo_extensions', to='djangocms_seo.opengraphmeta')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='djangocms_seo.seoextension')),
                ('twitter_meta', models.ManyToManyField(blank=True, related_name='seo_extensions', to='djangocms_seo.twittercardmeta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
