
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-25T22:18:51-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "711d18091f707146dbf93f01759e24b9d0ad272b",
 "version": "3.22.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
