# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.put_v1_ai_summarize_incident_incident_id_generated_summary_id_vote_request import PutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest

class TestPutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest(unittest.TestCase):
    """PutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest:
        """Test PutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest`
        """
        model = PutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest()
        if include_optional:
            return PutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest(
                direction = 'up'
            )
        else:
            return PutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest(
                direction = 'up',
        )
        """

    def testPutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest(self):
        """Test PutV1AiSummarizeIncidentIncidentIdGeneratedSummaryIdVoteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
