# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/ns/network-state-responses.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.ns.data import change_status_pb2 as zepben_dot_protobuf_dot_ns_dot_data_dot_change__status__pb2
from zepben.protobuf.ns.data import change_events_pb2 as zepben_dot_protobuf_dot_ns_dot_data_dot_change__events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0zepben/protobuf/ns/network-state-responses.proto\x12\x12zepben.protobuf.nm\x1a+zepben/protobuf/ns/data/change-status.proto\x1a+zepben/protobuf/ns/data/change-events.proto\"\xdc\x01\n\x18SetCurrentStatesResponse\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x12\x36\n\x07success\x18\x02 \x01(\x0b\x32#.zepben.protobuf.nm.BatchSuccessfulH\x00\x12\x36\n\x06paused\x18\x03 \x01(\x0b\x32$.zepben.protobuf.nm.ProcessingPausedH\x00\x12\x33\n\x07\x66\x61ilure\x18\x04 \x01(\x0b\x32 .zepben.protobuf.nm.BatchFailureH\x00\x42\x08\n\x06status\"c\n\x18GetCurrentStatesResponse\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x12\x34\n\x05\x65vent\x18\x02 \x03(\x0b\x32%.zepben.protobuf.nm.CurrentStateEventB/\n\x16\x63om.zepben.protobuf.nmP\x01\xaa\x02\x12Zepben.Protobuf.NMb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.ns.network_state_responses_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.zepben.protobuf.nmP\001\252\002\022Zepben.Protobuf.NM'
  _globals['_SETCURRENTSTATESRESPONSE']._serialized_start=163
  _globals['_SETCURRENTSTATESRESPONSE']._serialized_end=383
  _globals['_GETCURRENTSTATESRESPONSE']._serialized_start=385
  _globals['_GETCURRENTSTATESRESPONSE']._serialized_end=484
# @@protoc_insertion_point(module_scope)
