
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-26T23:13:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7cdae4eee0ab6c3b01a524181d3e8f00c1b63603",
 "version": "0.4.179"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
