
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-26T13:00:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b4a99dea092e9c04dc767701baccab85a668560",
 "version": "1.14.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
