# coding: utf-8

"""
    DeviceServer

    DeviceServer API  # noqa: E501

    The version of the OpenAPI document: 1.1.7
    Contact: david@3adesign.co.uk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import DeviceServer
from DeviceServer.models.get_attenuator_state200_response import GetAttenuatorState200Response  # noqa: E501
from DeviceServer.rest import ApiException

class TestGetAttenuatorState200Response(unittest.TestCase):
    """GetAttenuatorState200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetAttenuatorState200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = DeviceServer.models.get_attenuator_state200_response.GetAttenuatorState200Response()  # noqa: E501
        if include_optional :
            return GetAttenuatorState200Response(
                state = 1.337
            )
        else :
            return GetAttenuatorState200Response(
        )

    def testGetAttenuatorState200Response(self):
        """Test GetAttenuatorState200Response"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
