# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.patch_v1_integrations_aws_cloudtrail_batches_id import PatchV1IntegrationsAwsCloudtrailBatchesId

class TestPatchV1IntegrationsAwsCloudtrailBatchesId(unittest.TestCase):
    """PatchV1IntegrationsAwsCloudtrailBatchesId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchV1IntegrationsAwsCloudtrailBatchesId:
        """Test PatchV1IntegrationsAwsCloudtrailBatchesId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchV1IntegrationsAwsCloudtrailBatchesId`
        """
        model = PatchV1IntegrationsAwsCloudtrailBatchesId()
        if include_optional:
            return PatchV1IntegrationsAwsCloudtrailBatchesId(
                events_created = 56,
                status = '',
                error = '',
                ends_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PatchV1IntegrationsAwsCloudtrailBatchesId(
        )
        """

    def testPatchV1IntegrationsAwsCloudtrailBatchesId(self):
        """Test PatchV1IntegrationsAwsCloudtrailBatchesId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
