# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.patch_v1_teams_team_id_on_call_schedules_schedule_id import PatchV1TeamsTeamIdOnCallSchedulesScheduleId

class TestPatchV1TeamsTeamIdOnCallSchedulesScheduleId(unittest.TestCase):
    """PatchV1TeamsTeamIdOnCallSchedulesScheduleId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchV1TeamsTeamIdOnCallSchedulesScheduleId:
        """Test PatchV1TeamsTeamIdOnCallSchedulesScheduleId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchV1TeamsTeamIdOnCallSchedulesScheduleId`
        """
        model = PatchV1TeamsTeamIdOnCallSchedulesScheduleId()
        if include_optional:
            return PatchV1TeamsTeamIdOnCallSchedulesScheduleId(
                name = '',
                description = '',
                time_zone = '',
                member_ids = [
                    ''
                    ],
                slack_user_group_id = '',
                strategy = firehydrant_api_client.models.post_v1_teams_team_id_on_call_schedules_strategy.postV1TeamsTeamIdOnCallSchedules_strategy(
                    type = 'daily', 
                    handoff_time = '', 
                    handoff_day = 'monday', 
                    shift_duration = '', ),
                restrictions = [
                    firehydrant_api_client.models.post_v1_teams_team_id_on_call_schedules_restrictions_inner.postV1TeamsTeamIdOnCallSchedules_restrictions_inner(
                        start_day = 'monday', 
                        start_time = '', 
                        end_day = 'monday', 
                        end_time = '', )
                    ],
                effective_at = '',
                color = ''
            )
        else:
            return PatchV1TeamsTeamIdOnCallSchedulesScheduleId(
        )
        """

    def testPatchV1TeamsTeamIdOnCallSchedulesScheduleId(self):
        """Test PatchV1TeamsTeamIdOnCallSchedulesScheduleId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
