# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.integrations_aws_connection_entity_paginated import IntegrationsAwsConnectionEntityPaginated

class TestIntegrationsAwsConnectionEntityPaginated(unittest.TestCase):
    """IntegrationsAwsConnectionEntityPaginated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationsAwsConnectionEntityPaginated:
        """Test IntegrationsAwsConnectionEntityPaginated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationsAwsConnectionEntityPaginated`
        """
        model = IntegrationsAwsConnectionEntityPaginated()
        if include_optional:
            return IntegrationsAwsConnectionEntityPaginated(
                data = [
                    firehydrant_api_client.models.integrations_aws_connection_entity.Integrations_Aws_ConnectionEntity(
                        id = '', 
                        aws_account_id = '', 
                        target_arn = '', 
                        external_id = '', 
                        connection_status = 'pending_setup', 
                        status_text = '', 
                        status_description = '', 
                        environment_id = '', 
                        environment_name = '', 
                        regions = [
                            ''
                            ], )
                    ],
                pagination = firehydrant_api_client.models.pagination_entity.PaginationEntity(
                    count = 56, 
                    page = 56, 
                    items = 56, 
                    pages = 56, 
                    last = 56, 
                    prev = 56, 
                    next = 56, )
            )
        else:
            return IntegrationsAwsConnectionEntityPaginated(
        )
        """

    def testIntegrationsAwsConnectionEntityPaginated(self):
        """Test IntegrationsAwsConnectionEntityPaginated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
