
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import jneqsim.neqsim.fluidMechanics.flowSolver.twoPhaseFlowSolver.twoPhasePipeFlowSolver
import jneqsim.neqsim.fluidMechanics.flowSystem
import jneqsim.neqsim.thermo
import typing



class StirredCellSolver(jneqsim.neqsim.fluidMechanics.flowSolver.twoPhaseFlowSolver.twoPhasePipeFlowSolver.TwoPhasePipeFlowSolver, jneqsim.neqsim.thermo.ThermodynamicConstantsInterface):
    @typing.overload
    def __init__(self): ...
    @typing.overload
    def __init__(self, flowSystemInterface: jneqsim.neqsim.fluidMechanics.flowSystem.FlowSystemInterface, double: float, int: int): ...
    @typing.overload
    def __init__(self, flowSystemInterface: jneqsim.neqsim.fluidMechanics.flowSystem.FlowSystemInterface, double: float, int: int, boolean: bool): ...
    def calcFluxes(self) -> None: ...
    def clone(self) -> jneqsim.neqsim.fluidMechanics.flowSolver.twoPhaseFlowSolver.twoPhasePipeFlowSolver.TwoPhaseFixedStaggeredGridSolver: ...
    def initComposition(self, int: int, int2: int) -> None: ...
    def initFinalResults(self, int: int) -> None: ...
    def initMatrix(self) -> None: ...
    def initNodes(self) -> None: ...
    def initPhaseFraction(self, int: int) -> None: ...
    def initPressure(self, int: int) -> None: ...
    def initProfiles(self) -> None: ...
    def initTemperature(self, int: int) -> None: ...
    def initVelocity(self, int: int) -> None: ...
    def solveTDMA(self) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("jneqsim.neqsim.fluidMechanics.flowSolver.twoPhaseFlowSolver.stirredCellSolver")``.

    StirredCellSolver: typing.Type[StirredCellSolver]
