
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-25T13:53:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "02f24b4f69db67f428ca4ef0adb8327af5642c1e",
 "version": "2024.9.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
