# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.nunc_api import NuncApi


class TestNuncApi(unittest.TestCase):
    """NuncApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NuncApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v1_nunc_subscriptions_unsubscribe_token(self) -> None:
        """Test case for delete_v1_nunc_subscriptions_unsubscribe_token

        Unsubscribe from status page updates
        """
        pass

    def test_post_v1_nunc_subscriptions(self) -> None:
        """Test case for post_v1_nunc_subscriptions

        Subscribe to status page updates
        """
        pass


if __name__ == '__main__':
    unittest.main()
