# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.integrations_api import IntegrationsApi


class TestIntegrationsApi(unittest.TestCase):
    """IntegrationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IntegrationsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v1_integrations_slack_connections_connection_id_emoji_actions_emoji_action_id(self) -> None:
        """Test case for delete_v1_integrations_slack_connections_connection_id_emoji_actions_emoji_action_id

        Deletes a slack emoji action
        """
        pass

    def test_delete_v1_integrations_statuspage_connections_connection_id(self) -> None:
        """Test case for delete_v1_integrations_statuspage_connections_connection_id

        Delete a Statuspage connection
        """
        pass

    def test_get_v1_integrations(self) -> None:
        """Test case for get_v1_integrations

        """
        pass

    def test_get_v1_integrations_aws_cloudtrail_batches(self) -> None:
        """Test case for get_v1_integrations_aws_cloudtrail_batches

        List CloudTrail batches
        """
        pass

    def test_get_v1_integrations_aws_cloudtrail_batches_id(self) -> None:
        """Test case for get_v1_integrations_aws_cloudtrail_batches_id

        Retrieve a CloudTrail batch
        """
        pass

    def test_get_v1_integrations_aws_cloudtrail_batches_id_events(self) -> None:
        """Test case for get_v1_integrations_aws_cloudtrail_batches_id_events

        """
        pass

    def test_get_v1_integrations_aws_connections(self) -> None:
        """Test case for get_v1_integrations_aws_connections

        List AWS connections
        """
        pass

    def test_get_v1_integrations_aws_connections_id(self) -> None:
        """Test case for get_v1_integrations_aws_connections_id

        Retrieve an AWS connection
        """
        pass

    def test_get_v1_integrations_confluence_cloud_connections_id_space_search(self) -> None:
        """Test case for get_v1_integrations_confluence_cloud_connections_id_space_search

        Lists available space keys
        """
        pass

    def test_get_v1_integrations_connections(self) -> None:
        """Test case for get_v1_integrations_connections

        """
        pass

    def test_get_v1_integrations_field_maps_field_map_id_available_fields(self) -> None:
        """Test case for get_v1_integrations_field_maps_field_map_id_available_fields

        Get mappable fields
        """
        pass

    def test_get_v1_integrations_integration_id(self) -> None:
        """Test case for get_v1_integrations_integration_id

        """
        pass

    def test_get_v1_integrations_slack_connections_connection_id_emoji_actions(self) -> None:
        """Test case for get_v1_integrations_slack_connections_connection_id_emoji_actions

        Lists all slack emoji actions
        """
        pass

    def test_get_v1_integrations_slack_connections_connection_id_emoji_actions_emoji_action_id(self) -> None:
        """Test case for get_v1_integrations_slack_connections_connection_id_emoji_actions_emoji_action_id

        Retrieves a slack emoji action
        """
        pass

    def test_get_v1_integrations_slack_connections_connection_id_workspaces(self) -> None:
        """Test case for get_v1_integrations_slack_connections_connection_id_workspaces

        """
        pass

    def test_get_v1_integrations_slack_usergroups(self) -> None:
        """Test case for get_v1_integrations_slack_usergroups

        """
        pass

    def test_get_v1_integrations_statuses_slug(self) -> None:
        """Test case for get_v1_integrations_statuses_slug

        """
        pass

    def test_get_v1_integrations_statuspage_connections(self) -> None:
        """Test case for get_v1_integrations_statuspage_connections

        List Statuspage connections
        """
        pass

    def test_get_v1_integrations_statuspage_connections_connection_id(self) -> None:
        """Test case for get_v1_integrations_statuspage_connections_connection_id

        Retrieve a Statuspage connection
        """
        pass

    def test_get_v1_integrations_statuspage_connections_connection_id_pages(self) -> None:
        """Test case for get_v1_integrations_statuspage_connections_connection_id_pages

        """
        pass

    def test_get_v1_integrations_zendesk_search(self) -> None:
        """Test case for get_v1_integrations_zendesk_search

        """
        pass

    def test_patch_v1_integrations_aws_cloudtrail_batches_id(self) -> None:
        """Test case for patch_v1_integrations_aws_cloudtrail_batches_id

        Update a CloudTrail batch
        """
        pass

    def test_patch_v1_integrations_aws_connections_id(self) -> None:
        """Test case for patch_v1_integrations_aws_connections_id

        Update an AWS connection
        """
        pass

    def test_patch_v1_integrations_connections_slug_connection_id(self) -> None:
        """Test case for patch_v1_integrations_connections_slug_connection_id

        """
        pass

    def test_patch_v1_integrations_connections_slug_connection_id_refresh(self) -> None:
        """Test case for patch_v1_integrations_connections_slug_connection_id_refresh

        """
        pass

    def test_patch_v1_integrations_field_maps_field_map_id(self) -> None:
        """Test case for patch_v1_integrations_field_maps_field_map_id

        Update field map
        """
        pass

    def test_patch_v1_integrations_slack_connections_connection_id_emoji_actions_emoji_action_id(self) -> None:
        """Test case for patch_v1_integrations_slack_connections_connection_id_emoji_actions_emoji_action_id

        Updates a slack emoji action
        """
        pass

    def test_patch_v1_integrations_statuspage_connections_connection_id(self) -> None:
        """Test case for patch_v1_integrations_statuspage_connections_connection_id

        Update a Statuspage connection
        """
        pass

    def test_post_v1_integrations_connections_slug(self) -> None:
        """Test case for post_v1_integrations_connections_slug

        """
        pass

    def test_post_v1_integrations_slack_connections_connection_id_emoji_actions(self) -> None:
        """Test case for post_v1_integrations_slack_connections_connection_id_emoji_actions

        Creates a new slack emoji action
        """
        pass


if __name__ == '__main__':
    unittest.main()
