# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.post_v1_scheduled_maintenances_impacts_inner import PostV1ScheduledMaintenancesImpactsInner

class TestPostV1ScheduledMaintenancesImpactsInner(unittest.TestCase):
    """PostV1ScheduledMaintenancesImpactsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1ScheduledMaintenancesImpactsInner:
        """Test PostV1ScheduledMaintenancesImpactsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1ScheduledMaintenancesImpactsInner`
        """
        model = PostV1ScheduledMaintenancesImpactsInner()
        if include_optional:
            return PostV1ScheduledMaintenancesImpactsInner(
                type = '',
                id = '',
                condition_id = ''
            )
        else:
            return PostV1ScheduledMaintenancesImpactsInner(
                type = '',
                id = '',
                condition_id = '',
        )
        """

    def testPostV1ScheduledMaintenancesImpactsInner(self):
        """Test PostV1ScheduledMaintenancesImpactsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
