from src.api.utils.tools import users_create

if __name__ == "__main__":
    user = {
        "name": "nameA",  # 必填，用户登录后显示名称
        # 必填，用以在用户界面登录的信息以及通过api管理用户属性的id，
        # 如邮箱、工号、手机号等。如果使用邮箱登录，则此处填写邮箱，和下述email字段并不冲突。
        "loginId": "Id1",
        "password": "",  # SSO登录可不提供该字段信息，密码必须BASE64加密
        "role": "participant",  # 用户角色，目前可支持admin，editor，participant三类
        "email": "sample1@qq.email.com",
        "mobile": "13200000000",
        "enabled": True,  # 用户状态，非必填。布尔值，只能填True和false。True对应“启用”，false对应“禁用”。
        "userGroupIds": ["qb0d53da637bd4599ba6643d"],  # External group ID
        "userDefinedProperties": {
            "企业微信账号": "value2",
            "钉钉账号": "value2",
            "企业微信公司名称": "value2",
            "userMobile": "value2",
            "飞书账号": "value2",
            "关联数据集属性": "value2",
        },  # 观远平台内已经添加的用户属性名称
    }

    # user=  {
    # "name": "nameB",     # 必填，用户登录后显示名称
    # # 必填，用以在用户界面登录的信息以及通过api管理用户属性的id，
    # # 如邮箱、工号、手机号等。如果使用邮箱登录，则此处填写邮箱，和下述email字段并不冲突。
    # "loginId": "Id2",
    # "password": "",  #SSO登录可不提供该字段信息，密码必须BASE64加密
    # "role": "participant",   #用户角色，目前可支持admin，editor，participant三类
    # "email": "sample2@qq.email.com",
    # "mobile": "13200000000",
    # "enabled":True, #用户状态，非必填。布尔值，只能填True和false。True对应“启用”，false对应“禁用”。
    # "userGroupIds": [],    #External group ID
    # "userDefinedProperties": {
    #     "企业微信账号": "value2",
    #     "钉钉账号": "value2",
    #     "企业微信公司名称": "value2",
    #     "userMobile": "value2",
    #     "飞书账号": "value2",
    #     "关联数据集属性": "value2"
    #     }   #观远平台内已经添加的用户属性名称
    # }
    users = [user]

    users = [
        {
            "name": "孟旭霞",
            "loginId": "yunpu14750",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "319187"},
        },
        {
            "name": "aaaa",
            "loginId": "aaaa",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "319187"},
        },
    ]

    users = [
        {
            "name": "席永坡",
            "loginId": "yunpu3559",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110023"},
        },
        {
            "name": "杨骐玮",
            "loginId": "yunpu3561",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "110017,120009,120056",
            },
        },
        {
            "name": "陈媛",
            "loginId": "yunpu3562",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "331519,334516"},
        },
        {
            "name": "鹿海馨",
            "loginId": "yunpu3563",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110026"},
        },
        {
            "name": "朱晨阳",
            "loginId": "yunpu3564",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "334609"},
        },
        {
            "name": "黄旭子",
            "loginId": "yunpu3565",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "110027,110052,113679,116917",
            },
        },
        {
            "name": "吴潇琴",
            "loginId": "yunpu3566",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "331618"},
        },
        {
            "name": "李隆昌",
            "loginId": "yunpu3567",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330197"},
        },
        {
            "name": "邱祎",
            "loginId": "yunpu3568",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330507,339470"},
        },
        {
            "name": "孙立超",
            "loginId": "yunpu3569",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "110029,112789,113625",
            },
        },
        {
            "name": "高塘意",
            "loginId": "yunpu3570",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330413"},
        },
        {
            "name": "蒋龙",
            "loginId": "yunpu3571",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "330098,330099,330100,330357",
            },
        },
        {
            "name": "雷锋春",
            "loginId": "yunpu3572",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110030"},
        },
        {
            "name": "李士翔",
            "loginId": "yunpu3573",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "110032,111305,112812",
            },
        },
        {
            "name": "许然男",
            "loginId": "yunpu3574",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110033,110034"},
        },
        {
            "name": "尤欢",
            "loginId": "yunpu3575",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "339252"},
        },
        {
            "name": "顾红伟",
            "loginId": "yunpu3576",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110005,110035"},
        },
        {
            "name": "夏佳琪",
            "loginId": "yunpu3577",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330378"},
        },
        {
            "name": "金燕",
            "loginId": "yunpu3578",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110036,110045"},
        },
        {
            "name": "儲櫂坤",
            "loginId": "yunpu3579",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330014"},
        },
        {
            "name": "吕亚平",
            "loginId": "yunpu3580",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "110039,110048,110369",
            },
        },
        {
            "name": "黄晓敏",
            "loginId": "yunpu3581",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "330080,330227,330345,331913,338293",
            },
        },
        {
            "name": "刘海宁",
            "loginId": "yunpu3582",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110042"},
        },
        {
            "name": "杨卫兵",
            "loginId": "yunpu3583",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110046"},
        },
        {
            "name": "蒋胜利",
            "loginId": "yunpu3584",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "320622,330068,330205,330405",
            },
        },
        {
            "name": "周军",
            "loginId": "yunpu3585",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "110009,110047,110126,111932,114628",
            },
        },
        {
            "name": "乔秀梅",
            "loginId": "yunpu3587",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330062,330234"},
        },
        {
            "name": "刘琴",
            "loginId": "yunpu3588",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110051"},
        },
        {
            "name": "郑佳骏",
            "loginId": "yunpu3589",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330036"},
        },
        {
            "name": "张礼阳",
            "loginId": "yunpu3590",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "210013,215047"},
        },
        {
            "name": "夏依东",
            "loginId": "yunpu3591",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330208"},
        },
        {
            "name": "王颖",
            "loginId": "yunpu3592",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "111851,113109"},
        },
        {
            "name": "刘毓寰",
            "loginId": "yunpu3593",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "339370"},
        },
        {
            "name": "胡炜杰",
            "loginId": "yunpu3594",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330039"},
        },
        {
            "name": "包年彪",
            "loginId": "yunpu3595",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330445,333309"},
        },
        {
            "name": "张利华",
            "loginId": "yunpu3596",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "112247"},
        },
        {
            "name": "冯保宁",
            "loginId": "yunpu3597",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "112625"},
        },
        {
            "name": "刘盼",
            "loginId": "yunpu3598",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "111666"},
        },
        {
            "name": "陈琴",
            "loginId": "yunpu3599",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "331829"},
        },
        {
            "name": "赵一臣",
            "loginId": "yunpu3600",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "110543,113948"},
        },
        {
            "name": "周绮雯",
            "loginId": "yunpu3602",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "330093,330102,330105,330177,330190,330401,330423,330769,331812,332659,350010,350024,\
                350031,350081,350239,350677,352823,352926,353749,356818",
            },
        },
        {
            "name": "相飞",
            "loginId": "yunpu3603",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "116729"},
        },
        {
            "name": "陈宇",
            "loginId": "yunpu3604",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "113602"},
        },
        {
            "name": "刘小雅",
            "loginId": "yunpu3605",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "113456"},
        },
        {
            "name": "吴晓骏",
            "loginId": "yunpu3606",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {
                "省份": "",
                "城市": "",
                "门店": "330008,330021,330023,330268,330294,331948,335919",
            },
        },
        {
            "name": "秦倩倩",
            "loginId": "yunpu3607",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "112841,113548"},
        },
        {
            "name": "王华",
            "loginId": "yunpu3608",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "113768"},
        },
        {
            "name": "赵丽丽",
            "loginId": "yunpu3609",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "112701"},
        },
        {
            "name": "张静",
            "loginId": "yunpu3610",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "111005"},
        },
        {
            "name": "赵卫武",
            "loginId": "yunpu3611",
            "password": "",
            "role": "participant",
            "email": "",
            "mobile": "",
            "enabled": True,
            "userGroupIds": ["qb0d53da637bd4599ba6643d"],
            "userDefinedProperties": {"省份": "", "城市": "", "门店": "330379"},
        },
    ]

    msg = users_create(users)
    print(msg)
