
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-29T02:29:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bac3a18df3d8aac051ac832fc0d7d3d3c50e350",
 "version": "1.4.dev2439"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
