# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.post_v1_incidents_custom_fields_inner import PostV1IncidentsCustomFieldsInner

class TestPostV1IncidentsCustomFieldsInner(unittest.TestCase):
    """PostV1IncidentsCustomFieldsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1IncidentsCustomFieldsInner:
        """Test PostV1IncidentsCustomFieldsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1IncidentsCustomFieldsInner`
        """
        model = PostV1IncidentsCustomFieldsInner()
        if include_optional:
            return PostV1IncidentsCustomFieldsInner(
                field_id = '',
                value_string = '',
                value_array = [
                    ''
                    ]
            )
        else:
            return PostV1IncidentsCustomFieldsInner(
                field_id = '',
        )
        """

    def testPostV1IncidentsCustomFieldsInner(self):
        """Test PostV1IncidentsCustomFieldsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
