# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.patch_v1_services_service_id_functionalities_inner import PatchV1ServicesServiceIdFunctionalitiesInner

class TestPatchV1ServicesServiceIdFunctionalitiesInner(unittest.TestCase):
    """PatchV1ServicesServiceIdFunctionalitiesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchV1ServicesServiceIdFunctionalitiesInner:
        """Test PatchV1ServicesServiceIdFunctionalitiesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchV1ServicesServiceIdFunctionalitiesInner`
        """
        model = PatchV1ServicesServiceIdFunctionalitiesInner()
        if include_optional:
            return PatchV1ServicesServiceIdFunctionalitiesInner(
                id = '',
                remove = True,
                summary = ''
            )
        else:
            return PatchV1ServicesServiceIdFunctionalitiesInner(
        )
        """

    def testPatchV1ServicesServiceIdFunctionalitiesInner(self):
        """Test PatchV1ServicesServiceIdFunctionalitiesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
