# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from firehydrant_api_client.models.integrations_aws_connection_entity import IntegrationsAwsConnectionEntity
from typing import Optional, Set
from typing_extensions import Self

class IntegrationsAwsCloudtrailBatchEntity(BaseModel):
    """
    Integrations_Aws_CloudtrailBatchEntity model
    """ # noqa: E501
    id: Optional[StrictStr] = None
    events_created: Optional[StrictInt] = None
    status: Optional[StrictStr] = None
    starts_at: Optional[datetime] = None
    ends_at: Optional[datetime] = None
    connection: Optional[IntegrationsAwsConnectionEntity] = None
    created_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["id", "events_created", "status", "starts_at", "ends_at", "connection", "created_at"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['in_progress', 'failed', 'successful', 'pending', 'retried']):
            raise ValueError("must be one of enum values ('in_progress', 'failed', 'successful', 'pending', 'retried')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntegrationsAwsCloudtrailBatchEntity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of connection
        if self.connection:
            _dict['connection'] = self.connection.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntegrationsAwsCloudtrailBatchEntity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "events_created": obj.get("events_created"),
            "status": obj.get("status"),
            "starts_at": obj.get("starts_at"),
            "ends_at": obj.get("ends_at"),
            "connection": IntegrationsAwsConnectionEntity.from_dict(obj["connection"]) if obj.get("connection") is not None else None,
            "created_at": obj.get("created_at")
        })
        return _obj


