# This file was generated by setuptools-git-details.
# Do NOT change. Do NOT track in version control.
# Generated at: 2024-09-29T11:16:46.716658+00:00

from typing import Dict, Union

git: Dict[str, Union[str, bool]] = {
    "name": "setuptools-git-details",
    "revision": "279a66616debdda4914bb6837d2fd909f34a5aa4",
    "branch": "main",
    "tag": "1.0.0",
    "url": "https://github.com/marccarre/setuptools-git-details",
    "git": "git@github.com:marccarre/setuptools-git-details.git",
    "is_dirty": False,
}
__git__ = git
