# Generated by Django 4.2 on 2024-09-06 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeorders',
            name='master_agreement',
        ),
        migrations.RemoveField(
            model_name='workorders',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='workorders',
            name='expires_on',
        ),
        migrations.AddField(
            model_name='changeorders',
            name='work_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.workorders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorders',
            name='milestones',
            field=models.ManyToManyField(through='shared_models.WorkOrderMilestones', to='shared_models.milestones'),
        ),
        migrations.AlterField(
            model_name='changeorders',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.documenttypes'),
        ),
        migrations.AlterField(
            model_name='changeorders',
            name='service_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.servicedomains'),
        ),
        migrations.AlterField(
            model_name='changeorders',
            name='service_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.serviceregions'),
        ),
        migrations.AlterField(
            model_name='changeorders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Saved'), (2, 'Submitted')], default=1),
        ),
        migrations.AlterField(
            model_name='masteragreements',
            name='agreement_status',
            field=models.IntegerField(choices=[(1, 'Saved'), (2, 'Submitted')], default=1),
        ),
        migrations.AlterField(
            model_name='masteragreements',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 9, 6, 9, 45, 14, 277401, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masteragreements',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ratecards',
            name='status',
            field=models.IntegerField(choices=[(1, 'Saved'), (2, 'Submitted')]),
        ),
        migrations.AlterField(
            model_name='workorderresourcerates',
            name='work_order_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared_models.workorderresources'),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 9, 6, 9, 45, 20, 841636, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorders',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 6, 9, 45, 28, 42923, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorders',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='master_agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_orders', to='shared_models.masteragreements'),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='milestone_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.milestonetypes'),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='pricing_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.pricingmodels'),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='program_name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorders',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shared_models.servicetypes'),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 6, 9, 45, 38, 747297, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorders',
            name='work_order_status',
            field=models.IntegerField(choices=[(1, 'Saved'), (2, 'Submitted')], default=1),
        ),
    ]
