# Generated by Django 4.2 on 2024-09-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0004_remove_fileurls_file_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeorderfiles',
            name='change_order_file_id',
        ),
        migrations.RemoveField(
            model_name='workorderfiles',
            name='work_order_file_id',
        ),
        migrations.RemoveField(
            model_name='workorderfiles',
            name='work_order_reference_id',
        ),
        migrations.AddField(
            model_name='changeorderfiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorderfiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorders',
            name='files',
            field=models.ManyToManyField(through='shared_models.WorkOrderFiles', to='shared_models.fileurls'),
        ),
    ]
