# Generated by Django 4.2 on 2024-09-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0009_alter_changeorderresourcerates_change_order_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorderresourcerates',
            name='change_order_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_order_resource_rates', to='shared_models.changeorderresources'),
        ),
        migrations.AlterField(
            model_name='changeorderresources',
            name='change_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_order_resources', to='shared_models.changeorders'),
        ),
    ]
