
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-24T18:07:09-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1d1d51d357249a939b2b416a6956d4c191477b3",
 "version": "0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
