# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.post_mortems_api import PostMortemsApi


class TestPostMortemsApi(unittest.TestCase):
    """PostMortemsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostMortemsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v1_post_mortems_reports_report_id_reasons_reason_id(self) -> None:
        """Test case for delete_v1_post_mortems_reports_report_id_reasons_reason_id

        Delete a contributing factor
        """
        pass

    def test_get_v1_post_mortems_questions(self) -> None:
        """Test case for get_v1_post_mortems_questions

        List incident retrospective questions
        """
        pass

    def test_get_v1_post_mortems_questions_question_id(self) -> None:
        """Test case for get_v1_post_mortems_questions_question_id

        Get an incident retrospective question configured to be provided and filled out on each retrospective report.
        """
        pass

    def test_get_v1_post_mortems_reports(self) -> None:
        """Test case for get_v1_post_mortems_reports

        List all reports
        """
        pass

    def test_get_v1_post_mortems_reports_report_id(self) -> None:
        """Test case for get_v1_post_mortems_reports_report_id

        Get a report
        """
        pass

    def test_get_v1_post_mortems_reports_report_id_reasons(self) -> None:
        """Test case for get_v1_post_mortems_reports_report_id_reasons

        List contributing factors
        """
        pass

    def test_patch_v1_post_mortems_reports_report_id(self) -> None:
        """Test case for patch_v1_post_mortems_reports_report_id

        Update a report
        """
        pass

    def test_patch_v1_post_mortems_reports_report_id_fields_field_id(self) -> None:
        """Test case for patch_v1_post_mortems_reports_report_id_fields_field_id

        Update a field
        """
        pass

    def test_patch_v1_post_mortems_reports_report_id_reasons_reason_id(self) -> None:
        """Test case for patch_v1_post_mortems_reports_report_id_reasons_reason_id

        Update a contributing factor
        """
        pass

    def test_post_v1_post_mortems_reports(self) -> None:
        """Test case for post_v1_post_mortems_reports

        Create a report
        """
        pass

    def test_post_v1_post_mortems_reports_report_id_publish(self) -> None:
        """Test case for post_v1_post_mortems_reports_report_id_publish

        Publish a retrospective report
        """
        pass

    def test_post_v1_post_mortems_reports_report_id_reasons(self) -> None:
        """Test case for post_v1_post_mortems_reports_report_id_reasons

        Create contributing factor
        """
        pass

    def test_put_v1_post_mortems_questions(self) -> None:
        """Test case for put_v1_post_mortems_questions

        Update incident retrospective questions
        """
        pass

    def test_put_v1_post_mortems_reports_report_id_reasons_order(self) -> None:
        """Test case for put_v1_post_mortems_reports_report_id_reasons_order

        Reorder a contributing factor
        """
        pass


if __name__ == '__main__':
    unittest.main()
