# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.post_v1_webhooks import PostV1Webhooks

class TestPostV1Webhooks(unittest.TestCase):
    """PostV1Webhooks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1Webhooks:
        """Test PostV1Webhooks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1Webhooks`
        """
        model = PostV1Webhooks()
        if include_optional:
            return PostV1Webhooks(
                url = ''
            )
        else:
            return PostV1Webhooks(
                url = '',
        )
        """

    def testPostV1Webhooks(self):
        """Test PostV1Webhooks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
