# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.incident_tags_api import IncidentTagsApi


class TestIncidentTagsApi(unittest.TestCase):
    """IncidentTagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IncidentTagsApi()

    def tearDown(self) -> None:
        pass

    def test_get_v1_incident_tags(self) -> None:
        """Test case for get_v1_incident_tags

        List all incident tags
        """
        pass

    def test_post_v1_incident_tags_validate(self) -> None:
        """Test case for post_v1_incident_tags_validate

        Validate a list of tags
        """
        pass


if __name__ == '__main__':
    unittest.main()
