# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.severity_matrix_severity_matrix_entity import SeverityMatrixSeverityMatrixEntity

class TestSeverityMatrixSeverityMatrixEntity(unittest.TestCase):
    """SeverityMatrixSeverityMatrixEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeverityMatrixSeverityMatrixEntity:
        """Test SeverityMatrixSeverityMatrixEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SeverityMatrixSeverityMatrixEntity`
        """
        model = SeverityMatrixSeverityMatrixEntity()
        if include_optional:
            return SeverityMatrixSeverityMatrixEntity(
                matrix = [
                    firehydrant_api_client.models.severity_matrix_item_entity.SeverityMatrix_ItemEntity(
                        severity = '', 
                        condition_id = '', 
                        impact_id = '', 
                        impact_type = '', )
                    ],
                impacts = [
                    firehydrant_api_client.models.severity_matrix_impact_entity.SeverityMatrix_ImpactEntity(
                        id = '', 
                        name = '', 
                        type = '', 
                        affects_id = '', 
                        position = 56, )
                    ],
                conditions = [
                    firehydrant_api_client.models.severity_matrix_condition_entity.SeverityMatrix_ConditionEntity(
                        id = '', 
                        name = '', 
                        position = 56, )
                    ]
            )
        else:
            return SeverityMatrixSeverityMatrixEntity(
        )
        """

    def testSeverityMatrixSeverityMatrixEntity(self):
        """Test SeverityMatrixSeverityMatrixEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
