"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.7.5
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.request_rate import RequestRate
globals()['RequestRate'] = RequestRate
from apideck.model.virtual_webhooks import VirtualWebhooks


class TestVirtualWebhooks(unittest.TestCase):
    """VirtualWebhooks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVirtualWebhooks(self):
        """Test VirtualWebhooks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VirtualWebhooks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
