# Generated by Django 5.1 on 2024-09-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunk_upload', '0002_chunk_expire_time_chunk_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='completed/'),
        ),
    ]
