# Generated by Django 4.2.9 on 2024-09-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_tenant_settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
