# Autogenerated by devscripts/update-version.py

__version__ = '2024.09.24.232842'

RELEASE_GIT_HEAD = 'fa2be9a7c63babede07480151363e54eee5702bd'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.09.24.232842dev'
