# Generated by Django 4.2 on 2024-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0006_fileurls_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorders',
            name='files',
            field=models.ManyToManyField(through='shared_models.ChangeOrderFiles', to='shared_models.fileurls'),
        ),
        migrations.AddField(
            model_name='changeorders',
            name='milestones',
            field=models.ManyToManyField(through='shared_models.ChangeOrderMilestones', to='shared_models.milestones'),
        ),
    ]
