# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.nunc_component_entity import NuncComponentEntity

class TestNuncComponentEntity(unittest.TestCase):
    """NuncComponentEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NuncComponentEntity:
        """Test NuncComponentEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NuncComponentEntity`
        """
        model = NuncComponentEntity()
        if include_optional:
            return NuncComponentEntity(
                infrastructure_type = '',
                infrastructure_id = '',
                label = '',
                position = 56,
                component_group_id = ''
            )
        else:
            return NuncComponentEntity(
        )
        """

    def testNuncComponentEntity(self):
        """Test NuncComponentEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
