
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-26T12:39:18-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "f1c0032eb3d4a40ab28e14c0c9d56ca8e2c2de38",
 "version": "3.22.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
