# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.post_v1_incidents_incident_id_task_lists import PostV1IncidentsIncidentIdTaskLists

class TestPostV1IncidentsIncidentIdTaskLists(unittest.TestCase):
    """PostV1IncidentsIncidentIdTaskLists unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1IncidentsIncidentIdTaskLists:
        """Test PostV1IncidentsIncidentIdTaskLists
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1IncidentsIncidentIdTaskLists`
        """
        model = PostV1IncidentsIncidentIdTaskLists()
        if include_optional:
            return PostV1IncidentsIncidentIdTaskLists(
                task_list_id = '',
                assignee_id = ''
            )
        else:
            return PostV1IncidentsIncidentIdTaskLists(
                task_list_id = '',
        )
        """

    def testPostV1IncidentsIncidentIdTaskLists(self):
        """Test PostV1IncidentsIncidentIdTaskLists"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
