# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.report_entity import ReportEntity

class TestReportEntity(unittest.TestCase):
    """ReportEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportEntity:
        """Test ReportEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportEntity`
        """
        model = ReportEntity()
        if include_optional:
            return ReportEntity(
                data = [
                    firehydrant_api_client.models.reports_bucket_entity.Reports_BucketEntity(
                        bucket = '', 
                        points = [
                            firehydrant_api_client.models.reports_data_point_entity.Reports_DataPointEntity(
                                key = '', 
                                value = 56, )
                            ], )
                    ],
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                bucket_period = ''
            )
        else:
            return ReportEntity(
        )
        """

    def testReportEntity(self):
        """Test ReportEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
