# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.put_v1_runbooks_executions_execution_id_steps_step_id import PutV1RunbooksExecutionsExecutionIdStepsStepId

class TestPutV1RunbooksExecutionsExecutionIdStepsStepId(unittest.TestCase):
    """PutV1RunbooksExecutionsExecutionIdStepsStepId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutV1RunbooksExecutionsExecutionIdStepsStepId:
        """Test PutV1RunbooksExecutionsExecutionIdStepsStepId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutV1RunbooksExecutionsExecutionIdStepsStepId`
        """
        model = PutV1RunbooksExecutionsExecutionIdStepsStepId()
        if include_optional:
            return PutV1RunbooksExecutionsExecutionIdStepsStepId(
                state = '',
                schedule_for = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data = { },
                repeats_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PutV1RunbooksExecutionsExecutionIdStepsStepId(
                state = '',
        )
        """

    def testPutV1RunbooksExecutionsExecutionIdStepsStepId(self):
        """Test PutV1RunbooksExecutionsExecutionIdStepsStepId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
