# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.api.severity_matrix_api import SeverityMatrixApi


class TestSeverityMatrixApi(unittest.TestCase):
    """SeverityMatrixApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SeverityMatrixApi()

    def tearDown(self) -> None:
        pass

    def test_delete_v1_severity_matrix_conditions_condition_id(self) -> None:
        """Test case for delete_v1_severity_matrix_conditions_condition_id

        Delete a specific condition
        """
        pass

    def test_delete_v1_severity_matrix_impacts_impact_id(self) -> None:
        """Test case for delete_v1_severity_matrix_impacts_impact_id

        Delete a specific impact
        """
        pass

    def test_get_v1_severity_matrix(self) -> None:
        """Test case for get_v1_severity_matrix

        Retrieve your severity matrix
        """
        pass

    def test_get_v1_severity_matrix_conditions(self) -> None:
        """Test case for get_v1_severity_matrix_conditions

        Lists conditions
        """
        pass

    def test_get_v1_severity_matrix_conditions_condition_id(self) -> None:
        """Test case for get_v1_severity_matrix_conditions_condition_id

        """
        pass

    def test_get_v1_severity_matrix_impacts(self) -> None:
        """Test case for get_v1_severity_matrix_impacts

        Lists impacts
        """
        pass

    def test_patch_v1_severity_matrix(self) -> None:
        """Test case for patch_v1_severity_matrix

        Update your severity matrix
        """
        pass

    def test_patch_v1_severity_matrix_conditions_condition_id(self) -> None:
        """Test case for patch_v1_severity_matrix_conditions_condition_id

        Update a specific condition
        """
        pass

    def test_patch_v1_severity_matrix_impacts_impact_id(self) -> None:
        """Test case for patch_v1_severity_matrix_impacts_impact_id

        Update a specific impact
        """
        pass

    def test_post_v1_severity_matrix_conditions(self) -> None:
        """Test case for post_v1_severity_matrix_conditions

        Create condition
        """
        pass

    def test_post_v1_severity_matrix_impacts(self) -> None:
        """Test case for post_v1_severity_matrix_impacts

        Create impact
        """
        pass


if __name__ == '__main__':
    unittest.main()
