# coding: utf-8

"""
    FireHydrant API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firehydrant_api_client.models.post_v1_saved_searches_resource_type import PostV1SavedSearchesResourceType

class TestPostV1SavedSearchesResourceType(unittest.TestCase):
    """PostV1SavedSearchesResourceType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostV1SavedSearchesResourceType:
        """Test PostV1SavedSearchesResourceType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostV1SavedSearchesResourceType`
        """
        model = PostV1SavedSearchesResourceType()
        if include_optional:
            return PostV1SavedSearchesResourceType(
                name = '',
                is_private = True,
                filter_values = { }
            )
        else:
            return PostV1SavedSearchesResourceType(
                name = '',
                filter_values = { },
        )
        """

    def testPostV1SavedSearchesResourceType(self):
        """Test PostV1SavedSearchesResourceType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
