
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-19T20:44:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f657a5ce59f970287f270e9733e68f81fbee46f3",
 "version": "1.17.27.post0.dev6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
